version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  run-script:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Run a script"
          command: |
            echo "This is a demo script!"
            # Add any other commands or scripts you want to run here

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - run-script
